# Setup
title: vanna's blog
description: ""
url: "https://v4nn4.github.io"
baseurl: ""

# About/contact
author:
  name: ""
  url: "https://github.com/v4nn4"
  email: ""

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge