# Setup
title: vanna's blog
description: ""
url: "https://v4nn4.github.io"
baseurl: ""

# About/contact
author:
  name: ""
  url: "https://github.com/v4nn4"
  email: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
inter_post_navigation: true

# External gems
plugins: [jekyll-paginate]
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Github
github:
  repo: "https://github.com/v4nn4"